# -*- coding: utf-8 -*-
"""python1.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-SMBvkYkyINz_lHI15QtJZqCEhOb4xvg
"""

def side():
  a = int(input("Enter first side of  triangle: "))
  b = int(input("Enter second side of  triangle : "))
  c = int(input("Enter third side of  triangle : "))
  return a,b,c  
def area():
  a,b,c = side()
  print("Sides of triangle : ",a,b,c)
  s =(a+b+c)*0.5
  A= (s*(s-a)*(s-b)*(s-c))**0.5
  print("AREA OF TRIANGLE : ",A)
  return A
def  contribution():
 a1 =area()
 a2 =area()
 c1 =(a1/(a1+a2)*100)
 c2 =(a2/(a1+a2)*100)
 print("Contribution of first triangle : ",c1)
 print("Contribution of second triangle : ",c2)
contribution()