# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DKNd86qGkBHdwVubEJgEueAREkbE7t6T

5.Write a program to create a parent class,3D shapes,with methods printVolume() and printArea(),which prints the Volume and Area respectively.Create classes Cylinder and Sphere by inheriting 3Dshapes class.Using these child classes,calculate and print the Volume and Area of a Cylinder and Sphere
"""

#Base class
class  threeDShapes:
  def printVolume(show):
    print(" Volume is: ",show.Volume)
  def printArea(show):
    print(" Area is :",show.Area)
  
#Derived class used for the calculation of area and volume of cylinder
class Cylinder( threeDShapes):
  
  def __init__(show,r,h):
    show.Radius = r
    show.Height = h
  def calculate_Area(show):
    show.Area = 2*3.14*show.Radius*(show.Radius+show.Height)
  def calculate_Volume(show):
    show.Volume = round((3.14*show.Radius*show.Radius*show.Height),2)

#Derived class used for the calculation of area and volume of sphere
class Sphere( threeDShapes):
    
    def __init__(show,r):
      show.Radius = r
    def calculate_Area(show):
      show.Area = 4*3.14*show.Radius*show.Radius
    def calculate_Volume(show):
      show.Volume = round(((4/3)*3.14*(show.Radius**3)),2)


#creating object of class cylinder for the calculation of area and volume of cylinder
Radius_Cylinder = int(input("Enter the radius of the cylinder "))
Height_Cylinder = int(input("Enter the height of the cylinder "))
calcCylinder = Cylinder(Radius_Cylinder,Height_Cylinder)
calcCylinder.calculate_Area()
calcCylinder.printArea()
calcCylinder.calculate_Volume()
calcCylinder.printVolume()

#creating object of class cylinder for the calculation of area and volume of cylinder
RadiusSphere = int(input("\nEnter the radius of the sphere : "))
calcSphere = Sphere(RadiusSphere)
calcSphere.calculate_Area()
calcSphere.calculate_Volume()
calcSphere.printArea()
calcSphere.printVolume()