# -*- coding: utf-8 -*-
"""python1.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T8ZTr6whUYQO-9fACBxfGhRZBApHbrhn
"""

def Employdetails():
  name = str(input("Enter name of employee : "))
  code = int (input("Enter code of employee : "))
  basicpay = int(input("Enter basicpay of the employee"))
  
  
  
  print('------------------------PAYMENT SLIP-------------------------')
  print("Name of the employee : ",name)
  print("Code of the employee : ",code)  
  print("Basic pay  of the employee : ",basicpay) 
  return name,code,basicpay  
def calculate():
  name,code,basicpay=Employdetails()
  if basicpay<10000:
    GrossSalary= (basicpay+(5*2.5)+500)
    Deduction=(20+8+0)
    Netsalary=(GrossSalary-Deduction)
    print('Gross salary=',GrossSalary)
    print('Deduction=',Deduction)
    print('Net Salary=',NetSalary)
  elif basicpay>10000 and basicpay<30000:
    GrossSalary= (basicpay+(7.5*5)+2500) 
    Deduction=(60+8+0)
    NetSalary=(GrossSalary-Deduction)
    print('Gross salary=',GrossSalary)
    print('Deduction=',Deduction)
    print('Net Salary=',NetSalary)
  elif basicpay>30000 and basicpay<50000:
    GrossSalary= (basicpay+(11*7.5+5000)) 
    Deduction=(60+11+11)
    NetSalary=(GrossSalary-Deduction)
    print('Gross salary=',GrossSalary)
    print('Deduction=',Deduction)
    print('Net Salary=',NetSalary)
  else :
    GrossSalary= (basicpay+(25*11+7000))
    Deduction=(80+12+20)
    NetSalary=(GrossSalary-Deduction)
    print('Gross salary=',GrossSalary)
    print('Deduction=',Deduction)
    print('Net Salary=',NetSalary)
calculate()