# -*- coding: utf-8 -*-
"""python2.1.ipy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DXLfPMRU9n0TTVcliB2kTBAUBXKyXM01
"""

num=int(input("Enter number of months : "))
def fibonacci(num):

  if num==1:
    return 1
  elif num==2:
    return 1
  elif num>2:
    return fibonacci(num-1)+fibonacci(num-2)
fibonacci(num)    

print("Number of rabits upto " ,num,"months : ")
print('Month           Number of pair of rabits')  
for i in range(1,num+1):
   print(i,"\t\t",fibonacci(i))