# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vtzmPnV5GFMGt_uXLD5HC9j7Xj-EWr2b
"""

#4.Develop a program to perform 
 #a.define a function to check whether a number is happy or not
 #b.define a function to print all happy numbers within a range
 #c.define a function to print first N happy number
a=int(input('enter a number'))
def happy(a):
    num=a
    sum=ct=0
    default=False
    while ct<100:
      ct+=1
      while num!=0:
        r=num%10
        sum +=r*r
        num=num//10
        
    
      if sum==1: 
           default=True
           break
      else:
           num=sum
           sum=0
      return default  
    
if happy(a) == True:
    print('Happy')
else:
       
        
     print('Sad')
def range():
     ran1=int(input('enter starting range'))
     ran2=int(input('enter ending range'))
      
     for i in range(ran1, ran2):
       if happy(i)==True:
         print (i)
range()
def n_happy():
  n=int(input('enter how many happy members want to print'))
  print("first",n,"happy numbers are:")
  i=0
  while n!=0:
    i +=1
    if happy(i) ==True:
      n-=1
      print(i)

n_happy()