# -*- coding: utf-8 -*-
"""python1.5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A_48WAG8b3c6dIcTaOkHruifLJYzaAuT
"""

#5.Develop a program to read a string and perform the following operations:

#• Print all possible substring

#• Print all possible substrings of length K

#• Print all possible substrings of length K with N distinct characters

#• Print all palindrome substrings

def subString(p):
  for i in range(0,len(p)+1):
    for j in range(i+1,len(p)+1):
      s = p[i:j]
      print(s,end="  ")
def substringk(p,size):
  for i in range(0,len(p)+1):
    for j in range(i+1,len(p)+1):
      s = p[i:j]
      if len(s)==size:
        print(s,end="  ")
def substringN(p,size,N):
  for i in range(0,len(p)+1):
    for j in range(i+1,len(p)+1):
      s = p[i:j]
      if len(s)==size:
        distinct = set(s)
        if len(distinct) == N:
          print(s,end="  ")

def paliandrome(p):
  for i in range(0,len(p)+1):
    for j in range(i+1,len(p)+1):
      s = p[i:j]
      reverse = s[::-1]
      if reverse == s:
        print(s , end = "  ")


p = input("Enter the string :  ")
print("1.Sub Strings are")
subString(p)

length = int(input("\n\nEnter length of the substring "))
print("\n2.Sub Strings with length ",length," are")
substringk(p,length) 

num_of_distinct = int(input("\n\nEnter the no of distinct characters : "))
print("\n3.Sub Strings with length ",length,"and ",num_of_distinct," distinct characters are")
substringN(p,length,num_of_distinct)

print("\n\n4.The Paliandrome subStrings are ")
paliandrome(p)