# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZY-HnYWRN8aKxC-XYsyd_bhbTGWG07Ye

4.Develop a program to perform the following task:

a)Define a function to print all happy number is happy or not.

b)Define a function to print all happy numbers within a range

c)Define a function to printy first N happy numbers

A happy number is a number defined by the following process:

.Starting with any positive integer,replace the number with the sum of the squares of its digits.

.Repeat the process until the number equals 1(where it will stay),or it **loops endlessly in a cycle** which does not include 1.

.Those numbers for which this process ends in 1 are happy.

Note:if a number is not being happy after 100 iterations,consider it sad.
"""

a = int(input("Enter a number "))
def isHappy(a):
    n = a
    for i in range(100):
        sum = 0
        while n!= 0:
            r = n%10
            sum += r*r
            n = n//10
        n = sum
        if sum == 1:
           return True
    return False
if isHappy(a) == True:
    print("Happy")
else:
    print("Sad")
def happyr():
    l=int(input("Enter lower limit of the range: "))
    u=int(input("Enter upper limit of  the range: "))
    print("\nHappy numbers from ",l," to ",u," are: ")
    for i in range(l,u+1):
        if isHappy(i)==True:
           print(i)
happyr()

def happylist():
    p = int(input("\nEnter how many happy numbers do you want to print: "))
    print("First ",p," natural happy numbers are: ")
    i=0
    while p != 0:
        i += 1
        if isHappy(i) == True:
            p -= 1
            print(i)
happylist()