# -*- coding: utf-8 -*-
"""python1.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MLA4FHv5iEgiGh6cPGbIenqYC9eHuL3f
"""

numb = int(input("Enter a number "))
def isHappy(numb):
    n = numb
    for i in range(100):
        sum = 0
        while n!= 0:
            r = n%10
            sum += r*r
            n = n//10
        n = sum
        if sum == 1:
           return True
    return False
if isHappy(numb) == True:
    print("Happy!!!")
else:
    print("Sad!!!")
def happyr():
    l=int(input("\nEnter lower limit of range: "))
    u=int(input("Enter upper limit of range: "))
    print("\nHappy numbers from ",l," to ",u," are: ")
    for i in range(l,u+1):
        if isHappy(i)==True:
           print(i)
happyr()

def happylist():
    p = int(input("\nEnter how many happy numbers do you want to print: "))
    print("First ",p," natural happy numbers are: ")
    i=0
    while p != 0:
        i += 1
        if isHappy(i) == True:
            p -= 1
            print(i)
happylist()