# -*- coding: utf-8 -*-
"""python2.3.ipy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nDXYE98_ItQiHYf7S3nJYod-Ze9WHVPu
"""

import json
File_json=open('/iris.json','r')
Data = File_json.read()
List = json.loads(Data)

print("List having each line of json as elements")
print(List)
print("\n")

print("List of Dictionary objects")
for i in List:
  print(i)
print("\n")

print("Details of Setosa")
for i in List:
  if(i['species']=='setosa'):
    print(i)

listOfSpeciesName = list()
for i in List:
  listOfSpeciesName.append(i['species'])  
listOfSpeciesName = set(listOfSpeciesName)


print('\n')
sepal_area = list()
petal_area = list()
for i in listOfSpeciesName:
  print(i.capitalize())
  for j in List:
    if(j['species']==i):
      sepal_area.append(j['sepalLength']*j['sepalWidth'])
      petal_area.append(j['petalLength']*j['petalWidth'])
  print("Maximum Sepal Area in ",i.capitalize()," is ",round(max(sepal_area),2))
  print("Minimum Petal Area in ",i.capitalize()," is ",round(min(petal_area),2))  
  print('\n')
  sepal_area.clear()
  petal_area.clear()
print('\n')
ListCopy = list()
ListCopy = List
for i in ListCopy:
  petalArea = (i["petalLength"]*i["petalWidth"])
  sepalArea = (i["sepalLength"]*i["sepalWidth"])
  totalArea = (petalArea+sepalArea)
 
  i.update({'totalArea':totalArea})
sortedList = (sorted(ListCopy, key = lambda i:i['totalArea'] ))

print("The Sorted List")
for i in sortedList:
 
  print(i)

File_json.close()