# -*- coding: utf-8 -*-
"""python2.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D0g3fcNLS9MQD5FiFWCtpuV1A_ifwaz3

3.Read the file 'iris.json' as a text file:

       1.Create a list having each line of the file as an element

       2.Convert it into a list of dictionary objects

       3.Show the details of all flowers whose species is "setosa".

       4.Print the minimum petal area and max sepal area in each species 
       
       5.Sort the list of dictionaries according to the total area of sepal and petal
"""

#Creating list having each line of file as an element
x = open("iris.json","r")
y = x.readlines()
print(y)
import json
x = open("iris.json","r")
dictionary = json.load(x)
dictionary1 = dictionary
x.close()
print(dictionary)
#[print(i['species']) for i in dictionary]
for i in dictionary:
  if i['species'] == 'setosa':
    print(i)

l_species = []
for i in dictionary:
  if i['species'] not in l_species:
    l_species.append(i['species'])
print(l_species)

l_area_sepal1 = []
l_area_petal1 = []
l_area_sepal2 = []
l_area_petal2 = []
l_area_sepal3 = []
l_area_petal3 = []

for i in dictionary1:
  ptlarea = (i['sepalLength']*i['sepalWidth'])
  splarea = (i['petalLength']*i['petalWidth'])
  totalarea = ptlarea + splarea
  i.update({'totalArea' : totalarea}) 
  if i['species'] == l_species[0]:
    l_area_sepal1.append(i['sepalLength']*i['sepalWidth'])
    l_area_petal1.append(i['petalLength']*i['petalWidth'])
  elif i['species'] == l_species[1]:
    l_area_sepal2.append(i['sepalLength']*i['sepalWidth'])
    l_area_petal2.append(i['petalLength']*i['petalWidth'])
  elif i['species'] == l_species[2]:
    l_area_sepal3.append(i['sepalLength']*i['sepalWidth'])
    l_area_petal3.append(i['petalLength']*i['petalWidth'])


print(l_area_sepal1)
print(l_area_petal1)
print(l_area_sepal2)
print(l_area_sepal2)
print(l_area_sepal3)
print(l_area_sepal3)

print(l_species[0])
print("Greatest sepal area : ",max(l_area_sepal1))
print("Minimum petal area : ",min(l_area_petal1))
print(" ")
print(l_species[1])
print("Greatest sepal area : ",max(l_area_sepal2))
print("Minimum petal area : ",min(l_area_petal2))
print(" ")
print(l_species[2])
print("Greatest sepal area : ",max(l_area_sepal3))
print("Minimum petal area : ",min(l_area_petal3))

print(dictionary1)
sortedDictionary = (sorted(dictionary1, key = lambda i:i['totalArea'] ))
print(sortedDictionary)

for i in sortedDictionary:
  print(i)
  x.close()