# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16i5BNIRT02VO_x7v99KKsNZwyBxhowA4

4. Write a program to create a class Box with data members length,
breadth, height, area, and volume. Provider constructor that enables
initialization with one parameter (for cube), two parameters (for
square prism) three parameters (rectangular prism). Also, provide
functions to calculate area and volume.
Create a list of N boxes with random measurements and print the
details of the box with maximum volume: area ratio
"""

import random

class Box:
  def __init__(show,*arguments):
    
    if len(arguments) == 1:
      show.__length = arguments[0]
      show.__breadth = arguments[0]
      show.__height = arguments[0]
    
    elif len(arguments) == 2:
      show.__length = arguments[0]
      show.__breadth = arguments[0]
      show.__height = arguments[1]
    
    else:
      show.__length = arguments[0]
      show.__breadth = arguments[1]
      show.__height = arguments[2]

  
  def calculate_area(show):
    show.__area = show.__length*show.__breadth
    return show.__area
  
  def calculate_volume(show):
    show.__volume = show.__length*show.__breadth*show.__height
    return show.__volume
  
  def display_area(show):
    print("The area is ",show.__area)
  
  def display_volume(show):
    print("The volume is ",show.__volume,"\n")


ratio = []


cube_dimension = []
cube_dimension.append(random.randint(1,1000))
print("Cube Prism - Dimension" , end = " ")
print(cube_dimension)


cube_prism = Box(cube_dimension[0])
area1=cube_prism.calculate_area()
volume1=cube_prism.calculate_volume()
cube_prism.display_area()
cube_prism.display_volume()


ratio.append((volume1/area1))


square_dimension = []
for i in range(2):
  square_dimension.append(random.randint(1,1000))
print("Square Prism - Dimension" , end = " ")
print(square_dimension)


square_prism = Box(square_dimension[0],square_dimension[1])
area2=square_prism.calculate_area()
volume2=square_prism.calculate_volume()
square_prism.display_area()
square_prism.display_volume()


ratio.append((volume2/area2))


rectangular_dimension = []
for i in range(3):
  rectangular_dimension.append(random.randint(1,1000))


print("Rectangular Prism - Dimension" , end = " ")
print(rectangular_dimension)
rectangular_prism = Box(rectangular_dimension[0],rectangular_dimension[1],rectangular_dimension[2])
area3 = rectangular_prism.calculate_area()
volume3 = rectangular_prism.calculate_volume()
rectangular_prism.display_area()
rectangular_prism.display_volume()


ratio.append((volume3/area3))

index = ratio.index(max(ratio))


if index == 0:
  print("Cube Prism with Maximum Volume : Area - ", end=" ")
  print(cube_dimension)
elif index == 1:
  print("Square Prism with Maximum Volume : Area - " , end=" ")
  print(square_dimension)
else:
  print("Rectangular Prism with Maximum Volume : Area - ", end=" ")
  print(rectangular_dimension)