# -*- coding: utf-8 -*-
"""python2.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mGZgTydZmGP7mDjbXzVan6MR6dGd-pUf
"""

numbers = input("Enter the numbers : ")


numbersList = list(numbers.split(" "))



numList = []
for i in numbersList:
  numList.append(int(i))
print("List of numbers = ",numList)


n = int(input("Enter the number,n to rotate elements in a list n position to the right: "))
print("Rotated list ",end = " = ")
print(numList[-n:]+numList[:-n])


TupleList = tuple(numList)
print("Tuple = ",TupleList)


TupleList = tuple(set(TupleList))
numList = list(TupleList)
print("New list after removing duplicates  :  ",end = " = ")
print(numList)

values = []
for x in numList:
  values.append((x**2)-x)
print("Results of evalution the function ",end = " = ")
print(values)


finalList = numList + values
finalList.sort()
print("Merged list ",end = " = ")
print(finalList)