# -*- coding: utf-8 -*-
"""python3.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15etAewmN3RWCQ1ImUgFm3XWmJ5FAPQvD
"""

from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

def computePCA():
  #  number of rows and columns
  n, m = map(int, input("Enter rows and columns").split()) 
  #defining  matrix and taking input.
  A = array([input("Enter elements row by row ").strip().split() for _ in range(n)], int)
  print(A)
  # calculating the mean of each column
  M = mean(A, axis=0)
  # center columns by subtracting column means
  C = A - M
  # calculate covariance matrix of centered matrix
  V = cov(C.T)
  # eigendecomposition of covariance matrix
  values, vectors = eig(V)
  projection_matrix = (vectors.T[:][:2]).T
  # project data
  P = projection_matrix.T.dot(C.T)
  print(P.T)

computePCA()